id = "rhai"
name = "rhai"
version = "0.0.2"
schema_version = 1
authors = ["ElKowar <dev@elkowar.dev>"]
description = "Syntax highlighting for Rhai files."
repository = "https://github.com/elkowar/zed-rhai"

[grammars.rhai]
repository = "https://github.com/elkowar/tree-sitter-rhai"
rev = "4ac7384d487ffcb54e746ef1569585a749370c5b"
